# Generated by Django 4.1.1 on 2022-10-01 17:33

import django.db.models.deletion
from django.db import migrations, models

import django_plugins.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("django_plugins", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                (
                    "plugin",
                    django_plugins.fields.PluginField(
                        editable=False,
                        limit_choices_to={
                            "point__import_string": "mycmsproject.plugins.ContentType"
                        },
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_plugins.plugin",
                    ),
                ),
            ],
        ),
    ]
